#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-ruby-prof
Version  : 0.15.9
Release  : 6
URL      : https://rubygems.org/downloads/ruby-prof-0.15.9.gem
Source0  : https://rubygems.org/downloads/ruby-prof-0.15.9.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: rubygem-ruby-prof-bin
Requires: rubygem-ruby-prof-lib
BuildRequires : ruby
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake-compiler
BuildRequires : rubygem-rdoc

%description
= ruby-prof
{<img src="https://travis-ci.org/ruby-prof/ruby-prof.png?branch=master" alt="Build Status" />}[https://travis-ci.org/ruby-prof/ruby-prof]

%package bin
Summary: bin components for the rubygem-ruby-prof package.
Group: Binaries

%description bin
bin components for the rubygem-ruby-prof package.


%package lib
Summary: lib components for the rubygem-ruby-prof package.
Group: Libraries

%description lib
lib components for the rubygem-ruby-prof package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n ruby-prof-0.15.9
gem spec %{SOURCE0} -l --ruby > rubygem-ruby-prof.gemspec

%build
gem build rubygem-ruby-prof.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
ruby-prof-0.15.9.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/ruby-prof-0.15.8 && rake test && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/ruby-prof-0.15.9.gem
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/ruby-prof-0.15.9/gem.build_complete
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/ruby-prof-0.15.9/gem_make.out
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/ruby-prof-0.15.9/mkmf.log
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/CHANGES
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/bin/ruby-prof
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/bin/ruby-prof-check-trace
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/LICENSE.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/README_rdoc.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/Rack.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/Rack/RubyProf.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/RubyProf.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/RubyProf/AbstractPrinter.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/RubyProf/AggregateCallInfo.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/RubyProf/CallInfo.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/RubyProf/CallInfoPrinter.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/RubyProf/CallInfoVisitor.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/RubyProf/CallStackPrinter.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/RubyProf/CallTreePrinter.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/RubyProf/Cmd.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/RubyProf/DotPrinter.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/RubyProf/FlatPrinter.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/RubyProf/FlatPrinterWithLineNumbers.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/RubyProf/GraphHtmlPrinter.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/RubyProf/GraphPrinter.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/RubyProf/MethodInfo.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/RubyProf/MultiPrinter.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/RubyProf/Profile.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/RubyProf/ProfileTask.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/RubyProf/Thread.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/created.rid
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/css/fonts.css
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/css/rdoc.css
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/examples/flat_txt.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/examples/graph_html.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/examples/graph_txt.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/fonts/Lato-Light.ttf
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/fonts/Lato-LightItalic.ttf
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/fonts/Lato-Regular.ttf
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/fonts/Lato-RegularItalic.ttf
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/fonts/SourceCodePro-Bold.ttf
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/fonts/SourceCodePro-Regular.ttf
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/images/add.png
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/images/arrow_up.png
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/images/brick.png
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/images/brick_link.png
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/images/bug.png
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/images/bullet_black.png
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/images/bullet_toggle_minus.png
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/images/bullet_toggle_plus.png
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/images/date.png
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/images/delete.png
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/images/find.png
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/images/loadingAnimation.gif
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/images/macFFBgHack.png
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/images/package.png
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/images/page_green.png
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/images/page_white_text.png
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/images/page_white_width.png
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/images/plugin.png
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/images/ruby.png
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/images/tag_blue.png
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/images/tag_green.png
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/images/transparent.png
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/images/wrench.png
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/images/wrench_orange.png
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/images/zoom.png
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/index.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/js/darkfish.js
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/js/jquery.js
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/js/navigation.js
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/js/navigation.js.gz
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/js/search.js
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/js/search_index.js
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/js/search_index.js.gz
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/js/searcher.js
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/js/searcher.js.gz
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/doc/table_of_contents.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/examples/flat.txt
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/examples/graph.dot
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/examples/graph.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/examples/graph.txt
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/examples/multi.flat.txt
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/examples/multi.graph.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/examples/multi.grind.dat
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/examples/multi.stack.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/examples/stack.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/.RUBYARCHDIR.time
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/Makefile
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/extconf.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_call_info.c
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_call_info.h
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_call_info.o
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_measure.c
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_measure.h
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_measure.o
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_measure_allocations.c
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_measure_allocations.o
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_measure_cpu_time.c
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_measure_cpu_time.o
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_measure_gc_runs.c
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_measure_gc_runs.o
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_measure_gc_time.c
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_measure_gc_time.o
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_measure_memory.c
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_measure_memory.o
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_measure_process_time.c
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_measure_process_time.o
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_measure_wall_time.c
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_measure_wall_time.o
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_method.c
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_method.h
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_method.o
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_stack.c
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_stack.h
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_stack.o
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_thread.c
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_thread.h
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/rp_thread.o
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/ruby_prof.c
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/ruby_prof.h
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/ruby_prof.o
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/vc/ruby_prof.sln
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/vc/ruby_prof_18.vcxproj
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/vc/ruby_prof_19.vcxproj
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/vc/ruby_prof_20.vcxproj
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/lib/ruby-prof.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/lib/ruby-prof/aggregate_call_info.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/lib/ruby-prof/assets/call_stack_printer.css.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/lib/ruby-prof/assets/call_stack_printer.js.html
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/lib/ruby-prof/assets/call_stack_printer.png
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/lib/ruby-prof/call_info.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/lib/ruby-prof/call_info_visitor.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/lib/ruby-prof/compatibility.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/lib/ruby-prof/method_info.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/lib/ruby-prof/printers/abstract_printer.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/lib/ruby-prof/printers/call_info_printer.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/lib/ruby-prof/printers/call_stack_printer.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/lib/ruby-prof/printers/call_tree_printer.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/lib/ruby-prof/printers/dot_printer.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/lib/ruby-prof/printers/flat_printer.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/lib/ruby-prof/printers/flat_printer_with_line_numbers.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/lib/ruby-prof/printers/graph_html_printer.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/lib/ruby-prof/printers/graph_printer.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/lib/ruby-prof/printers/multi_printer.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/lib/ruby-prof/profile.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/lib/ruby-prof/rack.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/lib/ruby-prof/task.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/lib/ruby-prof/thread.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/lib/ruby-prof/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/lib/unprof.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ruby-prof.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/aggregate_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/basic_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/block_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/call_info_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/call_info_visitor_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/duplicate_names_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/dynamic_method_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/enumerable_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/exceptions_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/exclude_threads_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/fiber_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/issue137_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/line_number_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/measure_allocations_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/measure_cpu_time_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/measure_gc_runs_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/measure_gc_time_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/measure_memory_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/measure_process_time_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/measure_wall_time_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/method_elimination_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/module_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/multi_printer_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/no_method_class_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/pause_resume_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/prime.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/printers_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/printing_recursive_graph_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/rack_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/recursive_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/singleton_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/stack_printer_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/stack_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/start_stop_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/thread_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/unique_call_path_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/test/yarv_test.rb
/usr/lib64/ruby/gems/2.3.0/specifications/ruby-prof-0.15.9.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/ruby-prof
/usr/bin/ruby-prof-check-trace

%files lib
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/ruby-prof-0.15.9/ruby_prof.so
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/ext/ruby_prof/ruby_prof.so
/usr/lib64/ruby/gems/2.3.0/gems/ruby-prof-0.15.9/lib/ruby_prof.so
